if(EXISTS "C:/Users/Useres/Desktop/ce103-final-beyza-aydin-gokcenur-haymana-cpp/src/tests/utility/utility_tests[1]_tests.cmake")
  include("C:/Users/Useres/Desktop/ce103-final-beyza-aydin-gokcenur-haymana-cpp/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
